### ISSUE TITLE
Grocery Checklist

### ISSUE THREAD

**Issue by ryanjadhav** [ryanjadhav/half_dome_checklist#1]
# half_dome_checklist

General: 
- [ ] 4 extra gallons of water
- [ ] Ground up coffee
- [x] French press
- [x] Spike Ball
- [x] Water Filter
- [x] Sunscreen
- [ ] Camp lights (headlamps)
- [ ] Utensils
- [ ] plates, bowls, and cups

Friday Breakfast:
- [ ] Bagel
- [ ] Cream Cheese
- [ ] 6 Bananas

Friday Lunch:
- [ ] 6 Sandwiches
- [x] Turkey Jerky

Friday Dinner: 
- [ ] chicken
- [ ] cheese
- [ ] tortilla
- [ ] salsa
- [ ] chips
- [ ] sour cream? 

Saturday Breakfast:
- [ ] Bagel
- [ ] Cream Cheese
- [ ] 6 Bananas
- [ ] 6 muffins
- [ ] yogurt
- [ ] hard-boiled eggs

Saturday Lunch:
- [ ] 6 Sandwiches
- [ ] Turkey Jerky
- [ ] Kettle Maple Bacon Chips

Saturday Dinner: 
- [ ] chock dinner 

Sunday Breakfast:
- [ ] Eggs
- [ ] Bacon
- [ ] Hashbrowns

Sunday Lunch:
- [ ] Yosemite Grill?

**Comment by ryanjadhav** [comment]
![image](https://cloud.githubusercontent.com/assets/238376/8689270/357975ca-2a5a-11e5-89f2-f5c133e4bdc9.png)
